services:
  - type: web
    name: godivatech-backend
    env: node
    plan: free
    buildCommand: esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: false
    regions:
      - ohio